from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, JSON, ForeignKey
from sqlalchemy.orm import relationship
from datetime import datetime
from app.database import Base

class Job(Base):
    """
    Represents a single CSV upload and its processing job lifecycle.
    """
    __tablename__ = "jobs"
    
    id = Column(Integer, primary_key=True, index=True)
    filename = Column(String, nullable=False)
    status = Column(String, default="pending")  # pending, processing, completed, failed
    row_count_raw = Column(Integer, default=0)
    row_count_clean = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)
    error_message = Column(String, nullable=True)
    
    # Relationships
    transactions = relationship("Transaction", back_populates="job", cascade="all, delete-orphan")
    summary = relationship("JobSummary", back_populates="job", uselist=False, cascade="all, delete-orphan")

class Transaction(Base):
    """
    Represents a single parsed, cleaned, and enriched financial transaction record.
    """
    __tablename__ = "transactions"
    
    id = Column(Integer, primary_key=True, index=True)
    job_id = Column(Integer, ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False)
    
    # CSV fields
    txn_id = Column(String, nullable=True)
    date = Column(String, nullable=False) # Normalized to ISO 8601 YYYY-MM-DD
    merchant = Column(String, nullable=False)
    amount = Column(Float, nullable=False)
    currency = Column(String, nullable=False) # Normalized uppercase (INR/USD)
    status = Column(String, nullable=False) # Normalized uppercase (SUCCESS/FAILED/PENDING)
    category = Column(String, nullable=False) # Original or fallback
    account_id = Column(String, nullable=False)
    notes = Column(String, nullable=True)
    
    # Enrichment fields
    is_anomaly = Column(Boolean, default=False)
    anomaly_reason = Column(String, nullable=True)
    llm_category = Column(String, nullable=True)
    llm_raw_response = Column(String, nullable=True)
    llm_failed = Column(Boolean, default=False)
    
    # Relationships
    job = relationship("Job", back_populates="transactions")

class JobSummary(Base):
    """
    Stores the final aggregated metrics and LLM-generated narrative summary of the job.
    """
    __tablename__ = "job_summaries"
    
    id = Column(Integer, primary_key=True, index=True)
    job_id = Column(Integer, ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False, unique=True)
    
    total_spend_inr = Column(Float, default=0.0)
    total_spend_usd = Column(Float, default=0.0)
    top_merchants = Column(JSON, nullable=True)  # List of top merchants
    anomaly_count = Column(Integer, default=0)
    narrative = Column(String, nullable=True) # Narrative generated by Gemini
    risk_level = Column(String, nullable=True) # risk level generated by Gemini
    
    # Relationships
    job = relationship("Job", back_populates="summary")
